# Generated by Django 3.0.5 on 2020-12-02 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201202_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='role',
            field=models.CharField(choices=[('s', 'Student'), ('p', 'Professor')], max_length=9),
        ),
    ]
