# Generated by Django 3.0.5 on 2020-12-02 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0001_initial'),
        ('accounts', '0003_auto_20201202_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='post_made',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='component.Component'),
        ),
    ]
