# Generated by Django 3.0.5 on 2020-12-02 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('picture', models.ImageField(blank=True, upload_to='uploads')),
                ('category', models.CharField(default='', max_length=30)),
                ('manufacture_name', models.CharField(default='', max_length=50)),
                ('manufacture_num', models.CharField(default='', max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('datasheet', models.FileField(blank=True, upload_to='uploads')),
                ('review', models.CharField(default='', max_length=500)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfileInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='', max_length=50)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='component.Component')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(default='', max_length=500)),
                ('up_vote', models.IntegerField()),
                ('down_vote', models.IntegerField()),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='component.Component')),
                ('who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfileInfo')),
            ],
        ),
    ]
