# Generated by Django 3.0.5 on 2020-12-09 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0002_auto_20201203_1240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='component_comments',
        ),
    ]
