# Generated by Django 3.0.5 on 2020-12-09 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0003_auto_20201209_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='component_comments',
            new_name='comment',
        ),
    ]
