# Generated by Django 3.0.5 on 2020-12-09 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0004_auto_20201209_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='datasheet',
            field=models.FileField(blank=True, null=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='component',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
