# Generated by Django 3.0.5 on 2020-12-15 01:05

import component.models
from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0005_auto_20201209_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specification',
            name='component',
        ),
        migrations.AddField(
            model_name='component',
            name='comments',
            field=jsonfield.fields.JSONField(default=component.models.my_default),
        ),
        migrations.AddField(
            model_name='component',
            name='specifications',
            field=jsonfield.fields.JSONField(default=component.models.my_default),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Specification',
        ),
    ]
